### ISSUE TITLE
collision detection for HTML5

### ISSUE THREAD

**Issue by jack-jun** [TriAxis-Games/RealtimeMeshComponent#101]
Hello @Koderz,

Firstly really appreciate your work. 

I'm using this plugin to create the components at runtime, it works perfectly on desktop, but not on HTML5 for the collision detection, as your mentioned in the readme.

I would like to ask if it is possible to support this feature for Html5 or it's limited by the UE? And is there any alternatives?

Thank you so much

**Comment by Koderz** [comment]
Hey @jack-jun 

It will depend what you need, box/sphere/capsule collision should work fine in html5, convex and mesh collision require the physx cooker which I don't think can be compiled out to html5 correctly.  That would be an engine limitation, but I might try at some point seeing if I can get it to compile out.  Did you include the module "RuntimePhysXCooking" in your Build.cs file to see if it would include that correctly when it compiles.  That's on by default for desktop but not mobile/html5
