### ISSUE TITLE
Crash when creating mesh on MacOS 10.15.7 UE 25.3 RMC 4.1.4

### ISSUE THREAD

**Issue by wacintosh** [TriAxis-Games/RealtimeMeshComponent#193]
Running Example ABasicPMCStyleRMC

```
void ABasicPMCStyleRMC::OnConstruction(const FTransform& Transform)
{
     URuntimeMeshProviderStatic* StaticProvider = NewObject<URuntimeMeshProviderStatic>(this, TEXT("RuntimeMeshProvider-Static"));
     if (StaticProvider)
     {
         // The static provider should initialize before we use it
         GetRuntimeMeshComponent()->Initialize(StaticProvider);
 
         StaticProvider->SetupMaterialSlot(0, TEXT("TriMat"), Material);
 
 
         // This creates 3 positions for a triangle
         TArray<FVector> Positions{ FVector(0, -50, 0), FVector(0, 0, 100), FVector(0, 50, 0) };
 
         // This creates 3 vertex colors
         TArray<FColor> Colors{ FColor::Blue, FColor::Red, FColor::Green };
 
         // This indexes our simple triangle
         TArray<int32> Triangles = { 0, 1, 2 };
 
         TArray<FVector> EmptyNormals;
         TArray<FVector2D> EmptyTexCoords;
         TArray<FRuntimeMeshTangent> EmptyTangents;
         StaticProvider->CreateSectionFromComponents(0, 0, 0, Positions, Triangles, EmptyNormals, EmptyTexCoords, Colors, EmptyTangents, ERuntimeMeshUpdateFrequency::Infrequent, false);
     }
}
```

When running in xcode debugger points to RHICommandList.h

FORCEINLINE FIndexBufferRHIRef CreateIndexBuffer(uint32 Stride, uint32 Size, uint32 InUsage, FRHIResourceCreateInfo& CreateInfo)
    {
        return GDynamicRHI->CreateIndexBuffer_RenderThread(*this, Stride, Size, InUsage, CreateInfo);
    }

**Crashes here:**
0x14fe90c2f <+79>:  callq  0x14fe902a0               ; FMetalIndexBuffer::FMetalIndexBuffer(unsigned int, unsigned int, unsigned int)
->  0x14fe90c34 <+84>:  movq   -0x38(%rbp), %rbx

Assertion failed: (m_ptr), function Validate, file /Volumes/DataHD/Perforce/UE4/Release-4.25/Engine/Source/ThirdParty/mtlpp/mtlpp-master-7efad47/src/ns.hpp, line 115
og file open, 10/18/20 00:47:22

[log.log](https://github.com/TriAxis-Games/RuntimeMeshComponent/files/5397480/log.log)

**Comment by wacintosh** [comment]
Hi,

It seems that the crash is caused by line below. Commenting it out is a temp workaround at least for me to run [examples](https://github.com/TriAxis-Games/RuntimeMeshComponent-Examples).

[RuntimeMeshRendering.h](https://github.com/TriAxis-Games/RuntimeMeshComponent/blob/master/Source/RuntimeMeshComponent/Private/RuntimeMeshRendering.h)

**AdjacencyTrianglesBuffer = FRuntimeMeshIndexBuffer::CreateRHIBuffer<bIsInRenderThread>(AdjacencyTriangles, bShouldUseDynamicBuffers);**

**Comment by Koderz** [comment]
Closing as this is now a replaced version of the plugin so previous issues likely won't apply exactly. If you continue to have this issue on the new version, please feel free to reopen!

Thanks!
