### ISSUE TITLE
URuntimeMeshComponent RuntimeMeshReference is never initialized to nullptr

### ISSUE THREAD

**Issue by Matlauk** [TriAxis-Games/RealtimeMeshComponent#195]
URuntimeMeshComponent RuntimeMeshReference is never initialized to nullptr and as a result, EXCEPTION_ACCESS_VIOLATION exceptions are thrown when checking the value for nullptr.

**Comment by Koderz** [comment]
Closing as this is now a replaced version of the plugin so previous issues likely won't apply exactly. If you continue to have this issue on the new version, please feel free to reopen!

Thanks!
