### ISSUE TITLE
The model disappears after changing the scale

### ISSUE THREAD

**Issue by Mr-Devin** [TriAxis-Games/RealtimeMeshComponent#198]
https://user-images.githubusercontent.com/34890117/103076077-de1ba080-4607-11eb-8c00-ab5bbef22f7e.mov

**Comment by Koderz** [comment]
Closing as this is now a replaced version of the plugin so previous issues likely won't apply exactly. If you continue to have this issue on the new version, please feel free to reopen!

Thanks!
