### ISSUE TITLE
Unreal Engine is exiting due to D3D device being lost. (Error: 0x887A0006 - 'HUNG')

### ISSUE THREAD

**Issue by CitizenCEO** [TriAxis-Games/RealtimeMeshComponent#201]
Unreal engine crashes time to time due to D3D9 device being lost. This is not first time happening. Something has to be wrong.

![Bez názvu-1](https://user-images.githubusercontent.com/70374417/108623045-045d9100-743d-11eb-8f1b-ee3dc8919809.png)

**Comment by dave14124** [comment]
I am getting this as well. Can't use the examples project due to it constantly crashing with this error

**Comment by Moddingear** [comment]
I have the same crash when closing the editor in RuntimeMeshSandbox, that might have something to do with cleanup of informations when deleting actors.

**Comment by Johnly1986** [comment]
I also encountered the same problem, it happens when switching windows .

**Comment by CitizenCEO** [comment]
another random error report

`LoginId:359b4470413bd12ef199b8a893f744cb
EpicAccountId:5bee419182394ff79d7604e4dad06cfa

Fatal error: [File:E:/UE4_SRC/Engine/Source/Runtime/Windows/D3D11RHI/Private/D3D11Util.cpp] [Line: 198] Unreal Engine is exiting due to D3D device being lost. (Error: 0x887A0006 - 'HUNG')

UE4Editor_D3D11RHI!TerminateOnDeviceRemoved() [E:\UE4_SRC\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Util.cpp:208]
UE4Editor_D3D11RHI!VerifyD3D11Result() [E:\UE4_SRC\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Util.cpp:256]
UE4Editor_D3D11RHI!FD3D11DynamicRHI::RHIReadSurfaceFloatData() [E:\UE4_SRC\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11RenderTarget.cpp:894]
UE4Editor_RHI!FDynamicRHI::RHIReadSurfaceFloatData_RenderThread() [E:\UE4_SRC\Engine\Source\Runtime\RHI\Private\RHICommandList.cpp:2700]
UE4Editor_Renderer!ComputeSingleAverageBrightnessFromCubemap() [E:\UE4_SRC\Engine\Source\Runtime\Renderer\Private\ReflectionEnvironmentCapture.cpp:328]
UE4Editor_Renderer!ComputeAverageBrightness() [E:\UE4_SRC\Engine\Source\Runtime\Renderer\Private\ReflectionEnvironmentCapture.cpp:348]
UE4Editor_Renderer!TEnqueueUniqueRenderCommandType<`FScene::UpdateSkyCaptureContents'::`31'::FilterCommandName,<lambda_4af6bf976138f14f031facbd2e22dd79> >::DoTask() [E:\UE4_SRC\Engine\Source\Runtime\RenderCore\Public\RenderingThread.h:183]
UE4Editor_Renderer!TGraphTask<TEnqueueUniqueRenderCommandType<`FScene::UpdateSkyCaptureContents'::`31'::FilterCommandName,<lambda_4af6bf976138f14f031facbd2e22dd79> > >::ExecuteTask() [E:\UE4_SRC\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:886]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [E:\UE4_SRC\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:709]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [E:\UE4_SRC\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:601]
UE4Editor_RenderCore!RenderingThreadMain() [E:\UE4_SRC\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:373]
UE4Editor_RenderCore!FRenderingThread::Run() [E:\UE4_SRC\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:509]
UE4Editor_Core!FRunnableThreadWin::Run() [E:\UE4_SRC\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:86]`

**Comment by RonYanDaik** [comment]
I'm also having this issue.

```
D3D11: Removing Device.
Exception thrown at 0x00007FF9DCFA4F99 in UE4Editor-Win64-DebugGame.exe: Microsoft C++ exception: _com_error at memory location 0x000000ED715BA100.
Exception thrown at 0x00007FF9DCFA4F99 in UE4Editor-Win64-DebugGame.exe: Microsoft C++ exception: _com_error at memory location 0x000000ED715BA7B0.
Exception thrown at 0x00007FF9DCFA4F99 in UE4Editor-Win64-DebugGame.exe: Microsoft C++ exception: _com_error at memory location 0x000000ED715BAAB8.
Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/Windows/D3D11RHI/Private/D3D11Util.cpp] [Line: 198] 
Unreal Engine is exiting due to D3D device being lost. (Error: 0x887A0006 - 'HUNG')
```

RTX 3070

**Comment by xiejiangzhi** [comment]
I also encountered this problem

```
Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/Windows/D3D11RHI/Private/D3D11Util.cpp] [Line: 198] Unreal Engine is exiting due to D3D device being lost. (Error: 0x887A0006 - 'HUNG')

UE4Editor_D3D11RHI!TerminateOnDeviceRemoved() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Util.cpp:208]
UE4Editor_D3D11RHI!VerifyD3D11Result() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Util.cpp:256]
UE4Editor_D3D11RHI!CreateAndUpdatePooledUniformBuffer() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11UniformBuffer.cpp:152]
UE4Editor_D3D11RHI!FD3D11DynamicRHI::RHICreateUniformBuffer() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11UniformBuffer.cpp:192]
UE4Editor_SlateRHIRenderer!CreateSceneView() [D:\Build\++UE4\Sync\Engine\Source\Runtime\SlateRHIRenderer\Private\SlateRHIRenderingPolicy.cpp:252]
UE4Editor_SlateRHIRenderer!FSlateRHIRenderingPolicy::DrawElements() [D:\Build\++UE4\Sync\Engine\Source\Runtime\SlateRHIRenderer\Private\SlateRHIRenderingPolicy.cpp:652]
UE4Editor_SlateRHIRenderer!FSlateRHIRenderer::DrawWindow_RenderThread() [D:\Build\++UE4\Sync\Engine\Source\Runtime\SlateRHIRenderer\Private\SlateRHIRenderer.cpp:898]
UE4Editor_SlateRHIRenderer!TEnqueueUniqueRenderCommandType<`FSlateRHIRenderer::DrawWindows_Private'::`39'::SlateDrawWindowsCommandName,<lambda_f9feabdceba9d88a5c7b2ca3d59100d9> >::DoTask() [D:\Build\++UE4\Sync\Engine\Source\Runtime\RenderCore\Public\RenderingThread.h:183]
UE4Editor_SlateRHIRenderer!TGraphTask<TEnqueueUniqueRenderCommandType<`FSlateRHIRenderer::DrawWindows_Private'::`39'::SlateDrawWindowsCommandName,<lambda_f9feabdceba9d88a5c7b2ca3d59100d9> > >::ExecuteTask() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:886]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:710]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:602]
UE4Editor_RenderCore!RenderingThreadMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:373]
UE4Editor_RenderCore!FRenderingThread::Run() [D:\Build\++UE4\Sync\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:509]
UE4Editor_Core!FRunnableThreadWin::Run() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:86]
```

Win10, UE 4.27. Keep crashing when i use the example project.

**Comment by Koderz** [comment]
Closing as this is now a replaced version of the plugin so previous issues likely won't apply exactly. If you continue to have this issue on the new version, please feel free to reopen!

Thanks!
