### ISSUE TITLE
Crash on Hide/Show with Instances

### ISSUE THREAD

**Issue by caseyvan** [TriAxis-Games/RealtimeMeshComponent#207]
I ran into an odd crash while hiding, then showing two RuntimeMeshComponents that shared a RuntimeMesh. The specific issue was occurring in FRuntimeMeshComponentSceneProxy::CreateMeshBatch because Section.Buffers->VertexFactory was uninitialized. After some digging, it looked like the VertexFactory was being reset due to the reference count of that FRuntimeMeshSectionProxyBuffers instance dropping to zero. This was despite FRuntimeMeshProxy having a pointer to it, and no calls to clear up update that section. It looked to me like a race condition with reference counting, and adding ESPMode::ThreadSafe to FRuntimeMeshSectionProxyBuffers seems to have fixed it. I also noticed that FRuntimeMeshProxy is marked as thread-safe even though the section buffer was not.

**Comment by Moddingear** [comment]
Can you make a PR for it ?

**Comment by Koderz** [comment]
Closing as this is now a replaced version of the plugin so previous issues likely won't apply exactly. If you continue to have this issue on the new version, please feel free to reopen!

Thanks!
