### ISSUE TITLE
Can not run in the web with html5 packaged version

### ISSUE THREAD

**Issue by lx-onism** [TriAxis-Games/RealtimeMeshComponent#208]
Hello, I can run the game after packaging for Html5.   
There is the true web page：
![image](https://user-images.githubusercontent.com/32644256/114485841-328e6e80-9c3f-11eb-893f-eb1064eeff76.png)

it just always compiling...... And I can not get a solution。My UE4 version is 4.23
Please let me know if you have any idea about this, thanks.

**Comment by Moddingear** [comment]
This may be a limitation of either HTML or the engine, and I can't do anything without a proper log :/
Sorry !

**Comment by Moddingear** [comment]
Can you check if it's the same issue as with #209 ? Add the platform to the .uplugin file

**Comment by Koderz** [comment]
Closing as this is now a replaced version of the plugin so previous issues likely won't apply exactly. If you continue to have this issue on the new version, please feel free to reopen!

Thanks!
