### ISSUE TITLE
Error Launching on UE4.25

### ISSUE THREAD

**Issue by tdw46** [TriAxis-Games/RealtimeMeshComponent#210]
`Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Private/UObject/LinkerLoad.cpp] [Line: 3899] RuntimeMeshComponentStatic /Game/ProcMeshActorBp.Default__ProcMeshActorBp_C:asphaltMesh: Serial size mismatch: Got 12, Expected 32`

This error seems fixable. I just need to find the location of the declaration that causes this mismatch. Any help?

**Comment by Koderz** [comment]
Closing as this is now a replaced version of the plugin so previous issues likely won't apply exactly. If you continue to have this issue on the new version, please feel free to reopen!

Thanks!
