### ISSUE TITLE
build error  Version 4.1.4  UE 4.26    error C3861: “IsStaticPathAvailable”   not defined RuntimeMeshComponentProxy.cpp line 94  line 236

### ISSUE THREAD

**Issue by dragonpoint** [TriAxis-Games/RealtimeMeshComponent#214]
RuntimeMeshSandbox.uproject need rebuild MeshComponent but failed

open vs solution and build  got errors   error C3861: “IsStaticPathAvailable”   not defined  RuntimeMeshComponentProxy.cpp line 94  line 236

![UE4Editor_D8P5WiogIl](https://user-images.githubusercontent.com/6975520/118632729-49f2e580-b803-11eb-93bd-b34e0291c639.png)
![UE4Editor_GEMJFwcGBu](https://user-images.githubusercontent.com/6975520/118632740-4cedd600-b803-11eb-9f24-daba411a7fa2.png)

**Comment by trungus** [comment]
Hi, I have the same problem, any news ?

**Comment by Koderz** [comment]
Closing as this is now a replaced version of the plugin so previous issues likely won't apply exactly. If you continue to have this issue on the new version, please feel free to reopen!

Thanks!
