### ISSUE TITLE
Crash when slicing in UE5

### ISSUE THREAD

**Issue by BARKEM-JC** [TriAxis-Games/RealtimeMeshComponent#236]
Ran into the issue others have with slicing a mesh with multiple UVs, so i tried it on one UV and still crashes but with a different error. Both UE5 & Dev4.5 branches have this issue.

Using the RMCStatic comp, copy from static mesh, set simple collision for simulate physics, simulate physics, slice, crash
First exception using debugger, In SceneManagement:
L"MeshBatchElement 0, Material 'Material', index range extends past index buffer bounds: Start 0, Count 42, Buffer Size 72, Buffer stride 2"

Crash Log:
Assertion failed: GetAllocatorType() != FD3D12ResourceLocation::AT_Pool [File:D:\build\++UE5\Sync\Engine\Source\Runtime\D3D12RHI\Private\D3D12Resources.cpp] [Line: 768]

UnrealEditor_D3D12RHI!FD3D12ResourceLocation::Swap() [D:\build\++UE5\Sync\Engine\Source\Runtime\D3D12RHI\Private\D3D12Resources.cpp:768]
UnrealEditor_D3D12RHI!FD3D12Buffer::Swap() [D:\build\++UE5\Sync\Engine\Source\Runtime\D3D12RHI\Private\D3D12Buffer.cpp:494]
UnrealEditor_RHI!FRHICommandUpdateRHIResources::Execute() [D:\build\++UE5\Sync\Engine\Source\Runtime\RHI\Public\RHICommandListCommandExecutes.inl:666]
UnrealEditor_RHI!FRHICommand<FRHICommandUpdateRHIResources,FRHICommandUpdateRHIResourcesString2085>::ExecuteAndDestruct() [D:\build\++UE5\Sync\Engine\Source\Runtime\RHI\Public\RHICommandList.h:768]
UnrealEditor_RHI!FRHICommandListExecutor::ExecuteInner_DoExecute() [D:\build\++UE5\Sync\Engine\Source\Runtime\RHI\Private\RHICommandList.cpp:498]
UnrealEditor_RHI!FExecuteRHIThreadTask::DoTask() [D:\build\++UE5\Sync\Engine\Source\Runtime\RHI\Private\RHICommandList.cpp:560]
UnrealEditor_RHI!TGraphTask<FExecuteRHIThreadTask>::ExecuteTask() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:975]
UnrealEditor_Core!FNamedTaskThread::ProcessTasksNamedThread() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:753]
UnrealEditor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:642]
UnrealEditor_Core!FTaskGraphCompatibilityImplementation::ProcessThreadUntilRequestReturn() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:2115]
UnrealEditor_RenderCore!FRHIThread::Run() [D:\build\++UE5\Sync\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:325]
UnrealEditor_Core!FRunnableThreadWin::Run() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:146]

**Comment by KJY0714** [comment]
Any Progress?

RMCStatic comp, Copy static mesh to RM> Crash When Slicing. Same as what you asked.
RMC(No Static), Copy static mesh to RM> Slice not working.

Both are simulated physics. (simple convex collision)

**Comment by Koderz** [comment]
Closing as this is now a replaced version of the plugin so previous issues likely won't apply exactly. If you continue to have this issue on the new version, please feel free to reopen!

Thanks!
