### ISSUE TITLE
RealtimeMeshSimple.h Reference compilation failed in class

### ISSUE THREAD

**Issue by ripples-cz** [TriAxis-Games/RealtimeMeshComponent#244]
Even if I added a reference to a header file in a new C++ class, the compilation would not pass  .
Error:  "public: class TArray<unsigned char,class TSizedDefaultAllocator<32> > & __cdecl TArray<unsigned char,class TSizedDefaultAllocator<32> >::operator=(class TArray<unsigned char,class TSizedDefaultAllocator<32> > const &)" (??4?$TArray@EV?$TSizedDefaultAllocator@$0CA@@@@@QEAAAEAV0@AEBV0@@Z) 已经在 Module.EmergencyDrill.3_of_56.cpp.obj 中定义
  "public: __cdecl TArray<unsigned char,class TSizedDefaultAllocator<32> >::~TArray<unsigned char,class TSizedDefaultAllocator<32> >(void)" (??1?$TArray@EV?$TSizedDefaultAllocator@$0CA@@@@@QEAA@XZ) 已经在 Module.EmergencyDrill.3_of_56.cpp.obj 中定义
  "private: void __cdecl TArray<unsigned char,class TSizedDefaultAllocator<32> >::ResizeGrow(int)" (?ResizeGrow@?$TArray@EV?$TSizedDefaultAllocator@$0CA@@@@@AEAAXH@Z) 已经在 Module.EmergencyDrill.51_of_56.cpp.obj 中定义
  "private: void __cdecl TArray<unsigned char,class TSizedDefaultAllocator<32> >::ResizeForCopy(int,int)" (?ResizeForCopy@?$TArray@EV?$TSizedDefaultAllocator@$0CA@@@@@AEAAXHH@Z) 已经在 Module.EmergencyDrill.3_of_56.cpp.obj 中定义
  无法解析的外部符号 "__declspec(dllimport) public: void __cdecl TArray<unsigned char,class TSizedDefaultAllocator<32> >::Append(unsigned char const *,int)" (__imp_?Append@?$TArray@EV?$TSizedDefaultAllocator@$0CA@@@@@QEAAXPEBEH@Z)，函数 "class TArray<unsigned char,class TSizedDefaultAllocator<32> > __cdecl FStringToUint8(class FString const &)" (?FStringToUint8@@YA?AV?$TArray@EV?$TSizedDefaultAllocator@$0CA@@@@@AEBVFString@@@Z) 中引用了该符号

**Comment by Koderz** [comment]
I believe the RMC compiles correctly on all engine versions 5.0+ so I'm closing this.

If you continue to have any compilation, or other issues, feel free to open a new issue!

Thanks,
Koderz
