### ISSUE TITLE
Fatal error: [File:D:/UE4_SRC/Engine/Source/Runtime/Windows/D3D11RHI/Private/D3D11Util.cpp] [Line: 198] Unreal Engine is exiting due to D3D device being lost. (Error: 0x887A0006 - 'HUNG')

### ISSUE THREAD

**Issue by CitizenCEO** [TriAxis-Games/RealtimeMeshComponent#246]
There still seems to be issue with this error in particular

Full stacktrace here:

Fatal error: [File:D:/UE4_SRC/Engine/Source/Runtime/Windows/D3D11RHI/Private/D3D11Util.cpp] [Line: 198] Unreal Engine is exiting due to D3D device being lost. (Error: 0x887A0006 - 'HUNG')

UE4Editor_D3D11RHI!TerminateOnDeviceRemoved() [D:\UE4_SRC\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Util.cpp:208]
UE4Editor_D3D11RHI!VerifyD3D11Result() [D:\UE4_SRC\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Util.cpp:256]
UE4Editor_D3D11RHI!FD3D11DynamicRHI::GetQueryData() [D:\UE4_SRC\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Query.cpp:357]
UE4Editor_D3D11RHI!FD3D11RenderQueryBatcher::PerFrameFlush() [D:\UE4_SRC\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Query.cpp:45]
UE4Editor_D3D11RHI!FD3D11DynamicRHI::RHIPerFrameRHIFlushComplete() [D:\UE4_SRC\Engine\Source\Runtime\Windows\D3D11RHI\Private\Windows\WindowsD3D11Device.cpp:2086]
UE4Editor_RHI!FRHIResource::FlushPendingDeletes() [D:\UE4_SRC\Engine\Source\Runtime\RHI\Private\RHI.cpp:611]
UE4Editor_Renderer!FDeferredShadingSceneRenderer::Render() [D:\UE4_SRC\Engine\Source\Runtime\Renderer\Private\DeferredShadingRenderer.cpp:1456]
UE4Editor_Renderer!RenderViewFamily_RenderThread() [D:\UE4_SRC\Engine\Source\Runtime\Renderer\Private\SceneRendering.cpp:3619]
UE4Editor_Renderer!<lambda_ead3a0042dfdf5af6dd902d9545231b0>::operator()() [D:\UE4_SRC\Engine\Source\Runtime\Renderer\Private\SceneRendering.cpp:3889]
UE4Editor_Renderer!TEnqueueUniqueRenderCommandType<`FRendererModule::BeginRenderingViewFamily'::`35'::FDrawSceneCommandName,<lambda_ead3a0042dfdf5af6dd902d9545231b0> >::DoTask() [D:\UE4_SRC\Engine\Source\Runtime\RenderCore\Public\RenderingThread.h:183]
UE4Editor_Renderer!TGraphTask<TEnqueueUniqueRenderCommandType<`FRendererModule::BeginRenderingViewFamily'::`35'::FDrawSceneCommandName,<lambda_ead3a0042dfdf5af6dd902d9545231b0> > >::ExecuteTask() [D:\UE4_SRC\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:886]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [D:\UE4_SRC\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:709]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [D:\UE4_SRC\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:601]
UE4Editor_RenderCore!RenderingThreadMain() [D:\UE4_SRC\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:373]
UE4Editor_RenderCore!FRenderingThread::Run() [D:\UE4_SRC\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:509]
UE4Editor_Core!FRunnableThreadWin::Run() [D:\UE4_SRC\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:86]

I was able to completely avoid this error in past, two major things I changed: Mesh generation frequency changed infrequent to frequent + enabled SSGI

These two could be related to the error, i will try to rule out the SSGI because I am not 100% sure about it.

**Comment by CitizenCEO** [comment]
ERuntimeMeshUpdateFrequency::Infrequent -> this seems to solve the issue for now (which kinda sucks, because i need to be able to create vehicles very frequently....)

**Comment by Koderz** [comment]
This should be fixed in the newest version!

If you have this or any other issue in the future, feel free to open a new ticket!
