### ISSUE TITLE
vram not enough

### ISSUE THREAD

**Issue by Liuzhuoqiang** [TriAxis-Games/RealtimeMeshComponent#253]
I am using RuntimeMeshComponent v4.2 and ue4.26, I transfer the vertices data obtained by 3d reconstruction algorithm to ue4. In the tick function, i accept the data and reconstruct them by  CreateSectionFromComponents function. however, I found Excessive GPU memory consumption. May I ask how to solve this problem

**Comment by Liuzhuoqiang** [comment]
Is there a way to restrict the usage of gpu memory for ue4

**Comment by Koderz** [comment]
There's nothing directly limiting AFAIK, but without seeing what you're doing I can't really help much with that. Also at this point I can't really help much with UE4 and down and RMC4 as its been a while since I've touched either.
