### ISSUE TITLE
UE5.3 Packaging failed

### ISSUE THREAD

**Issue by 1157457050** [TriAxis-Games/RealtimeMeshComponent#263]
UATHelper: 打包 (Windows): [57/58] Link [x64] RMC531.exe
UATHelper: 打包 (Windows):   ���ڴ����� C:\Users\Administrator\Desktop\UE531\RMC531\Binaries\Win64\RMC531.lib �Ͷ��� C:\Users\Administrator\Desktop\UE531\RMC531\Binaries\Win64\RMC531.exp
LogSlate: Took 0.000175 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/NotoNaskhArabicUI-Regular.ttf' (144K)
LogSlate: Last resort fallback font was requested. Font: '../../../Engine/Content/Slate/Fonts/DroidSansFallback.ttf', Character: 'Ͷ (U+0376)'
LogSlate: Took 0.002154 seconds to synchronously load lazily loaded font '../../../Engine/Content/SlateDebug/Fonts/LastResort.ttf' (5269K)
UATHelper: 打包 (Windows): RealtimeMeshActor.cpp.obj : error LNK2019: �޷��������ⲿ���� "public: static class URealtimeMeshSubsystem * __cdecl URealtimeMeshSubsystem::GetInstance(class UWorld *)" (?GetInstance@URealtimeMeshSubsystem@@SAPEAV1@PEAVUWorld@@@Z)������ "public: virtual __cdecl ARealtimeMeshActor::~ARealtimeMeshActor(void)" (??1ARealtimeMeshActor@@UEAA@XZ) �������˸÷���
UATHelper: 打包 (Windows): C:\Users\Administrator\Desktop\UE531\RMC531\Binaries\Win64\RMC531.exe : fatal error LNK1120: 1 ���޷��������ⲿ����
UATHelper: 打包 (Windows): Total time in Parallel executor: 42.90 seconds

**Comment by Koderz** [comment]
Hey @1157457050 

This should be fixed in the latest version in master here on GitHub.

-Chris
