### ISSUE TITLE
Current version does not compile

### ISSUE THREAD

**Issue by laykun** [TriAxis-Games/RealtimeMeshComponent#276]
Module RealtimeMeshComponentExtensions added to uplugin file, however the module is not supplied in the repo. Build with a clean clone.

`Build started...
1>------ Build started: Project: U24, Configuration: DebugGame_Editor x64 ------
1>Using bundled DotNet SDK version: 6.0.302
1>Running UnrealBuildTool: dotnet "..\..\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" U24Editor Win64 DebugGame -Project="C:\Users\xxx\Documents\GitHub\u24\U24\U24.uproject" -WaitMutex -FromMsBuild
1>Log file: C:\Users\xxx\AppData\Local\UnrealBuildTool\Log.txt
1>Using 'git status' to determine working set for adaptive non-unity build (C:\Users\xxx\Documents\GitHub\u24).
1>Invalidating makefile for U24Editor (RealtimeMeshComponent.uplugin modified)
1>Total execution time: 0.55 seconds
1>Could not find definition for module 'RealtimeMeshComponentExtensions', (referenced via U24.uproject -> RealtimeMeshComponent.uplugin)
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command ""C:\Program Files\Epic Games\UE_5.3\Engine\Build\BatchFiles\Build.bat" U24Editor Win64 DebugGame -Project="C:\Users\xxx\Documents\GitHub\u24\U24\U24.uproject" -WaitMutex -FromMsBuild" exited with code 6.
1>Done building project "U24.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 10 up-to-date, 0 skipped ==========
========== Build started at 4:36 pm and took 00.976 seconds ==========`

**Comment by Koderz** [comment]
Hey @laykun  

I think this is fixed in latest! Hilariously I submitted that right as I got the notification for this coming through.

-Chris
