### ISSUE TITLE
Compilation fails on UE 5.3.2 due to function deprecation

### ISSUE THREAD

**Issue by laykun** [TriAxis-Games/RealtimeMeshComponent#277]
Just to make sure, I started a new fresh C++ project in UE 5.3.2, did a fresh clone from the repo and tried to compile. Attached build log.

[runtimemeshcomponent_532_build.log](https://github.com/TriAxis-Games/RealtimeMeshComponent/files/14479060/runtimemeshcomponent_532_build.log)

**Comment by laykun** [comment]
This uses a UE5.3.2 build from the Epic Games Launcher.

**Comment by Koderz** [comment]
Hey @laykun  

These should all be fixed at this point!

-Chris
