### ISSUE TITLE
Scale is not correct during mesh creation

### ISSUE THREAD

**Issue by ivl** [TriAxis-Games/RealtimeMeshComponent#279]
Let say we are create simple quad landscape 500x500 quads

const float QuadSize = 10.0f; // Size of each quad in Unreal units (cm)
for (int32 y = 0; y < 500; ++y)
{
    for (int32 x = 0; x < 500; ++x)
    {
        // Determine the world positions and heights for each corner of the quad

        float OriginX = x * QuadSize;
        float OriginY = y * QuadSize;

        // Define vertices with position, normal, tangent, color, and UV

        int32 V1 = Builder.AddVertex(FVector3f(OriginX, OriginY, 0.0f))
            .SetNormalAndTangent(FVector3f(0.0f, 0.0f, 1.0f), FVector3f(1.0f, 0.0f, 0.0f))
            .SetColor(FColor::White)
            .SetTexCoord(FVector2f(0.0f, 0.0f));

        int32 V2 = Builder.AddVertex(FVector3f(OriginX + QuadSize, OriginY, 0.0f))
            .SetNormalAndTangent(FVector3f(0.0f, 0.0f, 1.0f), FVector3f(1.0f, 0.0f, 0.0f))
            .SetColor(FColor::White)
            .SetTexCoord(FVector2f(1.0f, 0.0f));

        int32 V3 = Builder.AddVertex(FVector3f(OriginX, OriginY + QuadSize, 0.0f))
            .SetNormalAndTangent(FVector3f(0.0f, 0.0f, 1.0f), FVector3f(1.0f, 0.0f, 0.0f))
            .SetColor(FColor::White)
            .SetTexCoord(FVector2f(0.0f, 1.0f));

        int32 V4 = Builder.AddVertex(FVector3f(OriginX + QuadSize, OriginY + QuadSize, 0.0f))
            .SetNormalAndTangent(FVector3f(0.0f, 0.0f, 1.0f), FVector3f(1.0f, 0.0f, 0.0f))
            .SetColor(FColor::White)
            .SetTexCoord(FVector2f(1.0f, 1.0f));

        // Add triangles (ensure counter-clockwise winding order)
        Builder.AddTriangle(V1, V3, V2);
        Builder.AddTriangle(V2, V3, V4);
    }
}

Output result is not correct - ist longer over x axis than y. Should be square. if change count of quads from 500 to 100 its works well as expected. output correct suare plane.

**Comment by ivl** [comment]
got you. thanks for quick response. please close issue.

**Comment by Koderz** [comment]
You're welcome! Glad it helped!

-Chris
