### ISSUE TITLE
Crashes to desktop when loading the second "RealtimeMeshLatentUpdateTestActor"

### ISSUE THREAD

**Issue by Subash-Chandra** [TriAxis-Games/RealtimeMeshComponent#285]
LoginId:46743ace4d2c7c2757f9f1960ed9dc43
EpicAccountId:6a6a2569e4f74c52ab3494b87baf5ea8

Assertion failed: Stream.GetResourceDataSize() [File:D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\RealtimeMeshComponent\Public\RenderProxy\RealtimeMeshGPUBuffer.h] [Line: 88] 
This is the message that accompanies it.

UnrealEditor_RealtimeMeshComponent!RealtimeMesh::FRealtimeMeshSectionGroupStreamUpdateData::InitializeIfRequired() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\RealtimeMeshComponent\Public\RenderProxy\RealtimeMeshGPUBuffer.h:88]
UnrealEditor_RealtimeMeshComponent!RealtimeMesh::FRealtimeMeshSectionGroupProxy::CreateOrUpdateStream() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\RealtimeMeshComponent\Private\RenderProxy\RealtimeMeshSectionGroupProxy.cpp:92]
UnrealEditor_RealtimeMeshComponent!`RealtimeMesh::FRealtimeMeshProxyCommandBatch::AddSectionGroupTask'::`2'::<lambda_1>::operator()() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\RealtimeMeshComponent\Private\RenderProxy\RealtimeMeshProxyCommandBatch.cpp:153]
UnrealEditor_RealtimeMeshComponent!`RealtimeMesh::FRealtimeMeshProxyCommandBatch::AddLODTask'::`2'::<lambda_1>::operator()() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\RealtimeMeshComponent\Private\RenderProxy\RealtimeMeshProxyCommandBatch.cpp:139]
UnrealEditor_RealtimeMeshComponent!`RealtimeMesh::FRealtimeMeshProxyCommandBatch::Commit'::`2'::<lambda_1>::operator()() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\RealtimeMeshComponent\Private\RenderProxy\RealtimeMeshProxyCommandBatch.cpp:93]
UnrealEditor_RenderCore
UnrealEditor_RenderCore
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_RenderCore
UnrealEditor_RenderCore
UnrealEditor_Core
UnrealEditor_Core
kernel32
ntdll

**Comment by Koderz** [comment]
Hey @Subash-Chandra 

This should be fixed hopefully in latest! 

-Koderz
